version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/tests:/app/tests
    environment:
      - APP_DEBUG=true
      - PYTHONUNBUFFERED=1
    env_file:
      - ./backend/.env
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - voice-assistant

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
    environment:
      - VITE_WS_URL=ws://localhost:8000
    command: npm run dev -- --host
    networks:
      - voice-assistant

  # Future services
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - voice-assistant

  # prometheus:
  #   image: prom/prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  #   networks:
  #     - voice-assistant

networks:
  voice-assistant:
    driver: bridge